# in the templates via {{ site.myvariable }}.
title: Коллективный блог Ruby-разработчиков
description: >- # this means to ignore newlines until "baseurl:"
  Коллективный блог Ruby-программистов. Полезные материалы по стеку Ruby, Ruby on Rails, Sinatra, Padrino, Hanami, Crystal и т.д.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  krdprog

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

permalink: /:categories/:title/
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/